CREATE TABLE "COUNTRY" (
	"ID" VARCHAR2(4) NOT NULL,
	"COUNTRY_NAME" VARCHAR2(40) NOT NULL,
	CONSTRAINT "COUNTRY_PK" PRIMARY KEY ("ID")
);

CREATE TABLE "LANGUAGE" (
	"ID" NUMBER(4) NOT NULL,
	"LANG_NAME" VARCHAR2(25) NOT NULL,
	CONSTRAINT "LANGUAGE_PK" PRIMARY KEY ("ID"),
	CONSTRAINT "LANG_NAME_UNIQUE" UNIQUE ("LANG_NAME")
);

CREATE TABLE "USER" (
    "ID" NUMBER(3, 0) NOT NULL,
    "USER_NAME" VARCHAR2(128) NOT NULL,
    "PASSWORD" VARCHAR2(128) NOT NULL,
    "ENABLED" CHAR(1 BYTE) NOT NULL,
    "FIRST_NAME" VARCHAR2(30) NOT NULL,
    "LAST_NAME" VARCHAR2(50),
	"GENDER" VARCHAR2(6) NOT NULL,
	"COUNTRY_ID" VARCHAR2(4) NOT NULL,
    CONSTRAINT "USER_PK" PRIMARY KEY ("ID"),
    CONSTRAINT "ENABLED_CHECK" CHECK ("ENABLED" IN ('Y', 'N')),
    CONSTRAINT "UNIQUE_USER_NAME" UNIQUE ("USER_NAME") 
);

CREATE TABLE "USER_LANG" (
	"USER_ID" NUMBER(3, 0) NOT NULL,
	"LANG_ID" NUMBER(4) NOT NULL,
	CONSTRAINT "USER_ID_FK1" FOREIGN KEY ("USER_ID") REFERENCES "USER" ("ID"),
    CONSTRAINT "LANG_ID_FK" FOREIGN KEY ("LANG_ID") REFERENCES "LANGUAGE" ("ID"),
	CONSTRAINT "USER_LANG_UNIQUE" UNIQUE ("USER_ID", "LANG_ID")
);

CREATE TABLE "ROLE" (
   "ID" NUMBER(3, 0) NOT NULL,
   "ROLE_NAME" VARCHAR2(50) NOT NULL,
   CONSTRAINT "ROLE_PK" PRIMARY KEY ("ID")
);

CREATE TABLE "USER_ROLE" (
    "USER_ID" NUMBER(3, 0) NOT NULL,
    "ROLE_ID" NUMBER(3, 0) NOT NULL,
    CONSTRAINT "USER_ID_FK2" FOREIGN KEY ("USER_ID") REFERENCES "USER" ("ID"),
    CONSTRAINT "ROLE_ID_FK" FOREIGN KEY ("ROLE_ID") REFERENCES "ROLE" ("ID"),
	CONSTRAINT "USER_ROLE_UNIQUE" UNIQUE ("USER_ID", "ROLE_ID")
);

CREATE TABLE "SCHOOL" (
	"ID" NUMBER(3, 0) NOT NULL,
	"SCHOOL_CODE" VARCHAR2(10) NOT NULL,
	"SCHOOL_NAME" VARCHAR2(150) NOT NULL,
	"BOARD_FULL_NAME" VARCHAR2(100) NOT NULL,
	"BOARD_SHORT_NAME" VARCHAR2(15) NOT NULL,
	"ADDRESS" VARCHAR2(150) NOT NULL,
	"TYPE" VARCHAR2(30),
	CONSTRAINT "SCHOOL_PK" PRIMARY KEY ("ID"),
	CONSTRAINT "SCHOOL_CONE_UNIQUE" UNIQUE ("SCHOOL_CODE")
);

CREATE TABLE "IITJEE_RANK_HOLDER" (
	"ROLL_NO" NUMBER(4, 0) NOT NULL,
	"NAME" VARCHAR2(50) NOT NULL,
	"RANK" NUMBER(5) NOT NULL,
	"SCHOOL_ID" NUMBER(3, 0) NOT NULL,
	CONSTRAINT "IITJEE_RANK_HOLDER_PK" PRIMARY KEY ("ROLL_NO"),
	CONSTRAINT "SHOOL_ID_FK" FOREIGN KEY ("SCHOOL_ID") REFERENCES "SCHOOL" ("ID")
); 